# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: install
        verbose: false

    - task: Npm@1
      displayName: 'npm run build'
      inputs:
        command: custom
        verbose: false
        customCommand: 'run build'

    - task: PublishPipelineArtifact@1
      inputs:
        ArtifactName: 'drop'
        targetPath: 'build'
      displayName: Publish artifacts
    - task: AzureStaticWebApp@0
      displayName: Deploy to production environment
      inputs:
        app_location: 'build'
        skip_app_build: true
        azure_static_web_apps_api_token: $(deployment_token)  
# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'    
# - task: Npm@1
#   inputs:
#     command: 'install'
# - task: Npm@1
#   inputs:
#     command: 'custom'
#     customCommand: 'run build'

# - task: PublishBuildArtifacts@1    
#   displayName: 'Publish Artifact: drop'
#   inputs:
#     PathtoPublish: 'build'
# - task: AzureStaticWebApp@0
#   inputs:
#     azure_static_web_apps_api_token: '4fb9c76afa72c554346a15856f3593f5e8ff680ffc922cdf77d23e867044c5292-d7219642-c6c0-4577-ae66-2ee961b905a6003173872'
#     deployment_environment: 'Production'





 
