version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: adminPass123
      MYSQL_DATABASE: xultimate
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: adminPass123
      DB_NAME: xultimate
    ports:
      - "3000:3000"
