name: Node.js CI/CD workflow

on:
  push:
    branches:
      - main
env:
  DOCKER_COMPOSE_VERSION: 3.9
  DOCKER_BUILDKIT: 1      

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: CI=false npm run build
      - name: Test
        run: npm run test

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dockerproject:${{ github.sha }}
          
  build-and-push-docker-compose:
    runs-on: ubuntu-latest
    needs: [docker-build-and-push]

    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) \
        -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker Compose configuration
      run: |
        docker-compose build
        docker-compose push        
