name: Node.js CI/CD workflow

on:
  push:
    branches:
      - main
env:
  DOCKER_COMPOSE_VERSION: 2.2.1
  IMAGE_NAME: dudu49/dockerproject
  IMAGE_TAG: latest    

jobs:
          
  build-and-push-docker-compose-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Docker Compose
      uses: withlogicco/setup-compose-cli@v1
        
    - name: Build Docker image
      run: |
        docker-compose build
        docker tag $IMAGE_NAME $IMAGE_NAME:$IMAGE_TAG
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:latest
